ctrl_interface=/run/wpa_supplicant # change this if the runner is in other repostiory
update_config=1 # check file permissions to avoid wpa_cli being unable to configure it self

network = {
	scan_ssid = 1
	ssid=""
	psk=""
}
